name: GhostType
options:
  bundleIdPrefix: com.ghosttype
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  GhostType:
    type: application
    platform: macOS
    sources:
      - path: GhostType
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ghosttype.app
        PRODUCT_NAME: GhostType
        INFOPLIST_FILE: GhostType/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: GhostType/Resources/GhostType.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        ENABLE_HARDENED_RUNTIME: NO
